### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by anders-wind** [ptheywood/cuda-cmake-github-actions#6]
Hi Thanks a lot for putting this resource out here. 

Would it be possible for you to add a license to the repository? I think not having one means that only the copyright holder can use the code for whatever purpose.

https://choosealicense.com/ is a good resource by github for picking one :)

Thanks in advance

**Comment by ptheywood** [comment]
Thanks for highlighting this. 

I've now added the MIT license to the project (35d2536).
